version: '3.1'

services:

# 1개 인스턴스 (인스턴스 = 컴퓨터 라고 생각하면됨)
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k910419
    ports:
      - 27017:27017

  # 1개 인스턴스 (인스턴스 = 컴퓨터 라고 생각하면됨)
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:k910419@mongo:27017/
    depends_on:
      - mongo

  # 1개 인스턴스 (인스턴스 = 컴퓨터 라고 생각하면됨)
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: app-nodejs
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/data/node_mongo/app
    ports:
      - "9091:9091"
    depends_on:
      - mongo

#backend를 넣기전에는 local인데 backend를 넣으면 mongo임